// src/lib/mock-data.ts
// Mock data for KRS and Monitoring dashboards
// Story: Ops is the star (KRS 91, approval 94%), CEO/Finance solid,
//        Marketing needs work, Support just started.

import type { KRSAgent, MonitoredAgent, MonitoringSummary, OrgTrend } from './types'

export const krsAgents: KRSAgent[] = [
  {
    id: 'ceo-twin',
    role: 'CEO / General Manager',
    name: 'Martín García',
    avatar: 'MG',
    krs: 87,
    mode: 'assisted',
    dimensions: {
      completitud: 90,
      especificidad: 85,
      consistencia: 92,
      unicidad: 95,
      temporalidad: 78,
    },
    tasksDocumented: 12,
    tasksExpected: 14,
    tasksBySource: { screenLearning: 8, chat: 4 },
    screenHours: 6.5,
    gaps: [
      'New vendor evaluation process',
      'Discount approval criteria >15%',
    ],
    lastObservation: '2026-04-14T14:22:00',
    onboardingDuration: '6.5 hrs observation + 18 min chat',
  },
  {
    id: 'marketing-twin',
    role: 'Marketing Manager',
    name: 'Lucía Fernández',
    avatar: 'LF',
    krs: 72,
    mode: 'shadow',
    dimensions: {
      completitud: 68,
      especificidad: 75,
      consistencia: 80,
      unicidad: 60,
      temporalidad: 72,
    },
    tasksDocumented: 8,
    tasksExpected: 12,
    tasksBySource: { screenLearning: 5, chat: 3 },
    screenHours: 3.2,
    gaps: [
      'Audience segmentation criteria',
      'Content approval process',
      'Ad budget management',
      'Editorial calendar',
    ],
    lastObservation: '2026-04-14T13:45:00',
    onboardingDuration: '3.2 hrs observation + 12 min chat',
    overlapWarning: "Overlap with Support on 'social media response'",
  },
  {
    id: 'ops-twin',
    role: 'Operations / Logistics',
    name: 'Carlos Méndez',
    avatar: 'CM',
    krs: 91,
    mode: 'assisted',
    dimensions: {
      completitud: 95,
      especificidad: 88,
      consistencia: 94,
      unicidad: 90,
      temporalidad: 85,
    },
    tasksDocumented: 10,
    tasksExpected: 10,
    tasksBySource: { screenLearning: 7, chat: 3 },
    screenHours: 8.0,
    gaps: [],
    lastObservation: '2026-04-14T14:50:00',
    onboardingDuration: '8 hrs observation + 22 min chat',
  },
  {
    id: 'finance-twin',
    role: 'Finance / Administration',
    name: 'Ana Ruiz',
    avatar: 'AR',
    krs: 83,
    mode: 'assisted',
    dimensions: {
      completitud: 85,
      especificidad: 82,
      consistencia: 88,
      unicidad: 92,
      temporalidad: 75,
    },
    tasksDocumented: 9,
    tasksExpected: 11,
    tasksBySource: { screenLearning: 6, chat: 3 },
    screenHours: 5.5,
    gaps: [
      'Monthly accounting close process',
      'Expense categorization criteria',
    ],
    lastObservation: '2026-04-14T14:10:00',
    onboardingDuration: '5.5 hrs observation + 20 min chat',
  },
  {
    id: 'support-twin',
    role: 'Customer Support',
    name: 'Diego López',
    avatar: 'DL',
    krs: 64,
    mode: 'shadow',
    dimensions: {
      completitud: 55,
      especificidad: 70,
      consistencia: 75,
      unicidad: 58,
      temporalidad: 68,
    },
    tasksDocumented: 5,
    tasksExpected: 9,
    tasksBySource: { screenLearning: 2, chat: 3 },
    screenHours: 1.5,
    gaps: [
      'Claims escalation protocol',
      'Response SLA per channel',
      'Returns process',
      'Product knowledge base',
    ],
    lastObservation: '2026-04-14T11:30:00',
    onboardingDuration: '1.5 hrs observation + 8 min chat',
    overlapWarning: "Overlap with Marketing on 'social media response'",
  },
]

export const monitoringSummary: MonitoringSummary = {
  totalAgents: 5,
  activeAgents: 5,
  totalProposals: 147,
  totalApproved: 118,
  totalRejected: 29,
  avgApprovalRate: 80.3,
  totalTokensUsed: 2847500,
  totalCost: 42.71,
  avgConfidence: 0.74,
  avgTimeToResolution: '4.2h',
  automationRate: 34,
  alertsActive: 3,
  totalScreenHours: 24.7,
  screenLearningRate: 1.8,
  costPerScreenHour: 0.85,
}

export const monitoredAgents: MonitoredAgent[] = [
  {
    id: 'ceo-twin',
    role: 'CEO / General Manager',
    name: 'Martín García',
    mode: 'assisted',
    metrics: {
      approvalRate: 88,
      proposals: 32,
      approved: 28,
      rejected: 4,
      costPerAction: 0.38,
      totalCost: 12.16,
      tokensUsed: 810500,
      confidenceAvg: 0.82,
      timeToResolution: '2.1h',
      knowledgeCoverage: 86,
      automationRate: 42,
      errorRate: 3.1,
      screenHours: 6.5,
      tasksFromScreen: 8,
      screenEfficiency: 1.23,
    },
    weeklyTrend: [75, 78, 82, 85, 88],
    alerts: [],
  },
  {
    id: 'marketing-twin',
    role: 'Marketing Manager',
    name: 'Lucía Fernández',
    mode: 'shadow',
    metrics: {
      approvalRate: 65,
      proposals: 40,
      approved: 26,
      rejected: 14,
      costPerAction: 0.55,
      totalCost: 14.3,
      tokensUsed: 953500,
      confidenceAvg: 0.58,
      timeToResolution: '6.8h',
      knowledgeCoverage: 67,
      automationRate: 18,
      errorRate: 7.2,
      screenHours: 3.2,
      tasksFromScreen: 5,
      screenEfficiency: 1.56,
    },
    weeklyTrend: [72, 70, 68, 67, 65],
    alerts: [
      { type: 'critical', message: 'Approval rate < 70% (65%)', metric: 'approvalRate' },
      { type: 'warning', message: 'Cost per action > $0.50 ($0.55)', metric: 'costPerAction' },
      {
        type: 'critical',
        message: 'Error rate > 5% (7.2%) — consider reverting to Shadow Mode',
        metric: 'errorRate',
      },
    ],
  },
  {
    id: 'ops-twin',
    role: 'Operations / Logistics',
    name: 'Carlos Méndez',
    mode: 'assisted',
    metrics: {
      approvalRate: 94,
      proposals: 35,
      approved: 33,
      rejected: 2,
      costPerAction: 0.22,
      totalCost: 7.7,
      tokensUsed: 513500,
      confidenceAvg: 0.89,
      timeToResolution: '1.5h',
      knowledgeCoverage: 100,
      automationRate: 55,
      errorRate: 0,
      screenHours: 8.0,
      tasksFromScreen: 7,
      screenEfficiency: 0.88,
    },
    weeklyTrend: [88, 90, 91, 93, 94],
    alerts: [],
  },
  {
    id: 'finance-twin',
    role: 'Finance / Administration',
    name: 'Ana Ruiz',
    mode: 'assisted',
    metrics: {
      approvalRate: 82,
      proposals: 22,
      approved: 18,
      rejected: 4,
      costPerAction: 0.31,
      totalCost: 5.58,
      tokensUsed: 372000,
      confidenceAvg: 0.76,
      timeToResolution: '3.8h',
      knowledgeCoverage: 82,
      automationRate: 36,
      errorRate: 2.4,
      screenHours: 5.5,
      tasksFromScreen: 6,
      screenEfficiency: 1.09,
    },
    weeklyTrend: [76, 78, 79, 81, 82],
    alerts: [],
  },
  {
    id: 'support-twin',
    role: 'Customer Support',
    name: 'Diego López',
    mode: 'shadow',
    metrics: {
      approvalRate: 72,
      proposals: 18,
      approved: 13,
      rejected: 5,
      costPerAction: 0.18,
      totalCost: 2.34,
      tokensUsed: 198000,
      confidenceAvg: 0.55,
      timeToResolution: '8.5h',
      knowledgeCoverage: 56,
      automationRate: 12,
      errorRate: 4.8,
      screenHours: 1.5,
      tasksFromScreen: 2,
      screenEfficiency: 1.33,
    },
    weeklyTrend: [68, 69, 70, 71, 72],
    alerts: [
      { type: 'warning', message: 'Confidence score < 0.6 (0.55)', metric: 'confidenceAvg' },
      { type: 'warning', message: 'Knowledge coverage < 60% (56%)', metric: 'knowledgeCoverage' },
    ],
  },
]

export const orgTrend: OrgTrend = {
  labels: ['Wk 1', 'Wk 2', 'Wk 3', 'Wk 4', 'Wk 5'],
  approvalRate: [76, 78, 80, 81, 80.3],
  costTotal: [28.5, 32.1, 35.8, 39.2, 42.71],
  automationRate: [15, 20, 25, 30, 34],
  screenLearningRate: [0.8, 1.1, 1.4, 1.6, 1.8],
}
